import type { Metadata } from "next"
import dynamic from "next/dynamic"
import { Inter as FontSans } from "next/font/google"

import { cn } from "./_lib/utils"
import "./globals.css"

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const ClientOnlyContext = dynamic(() => import("./_context/root-context"), {
  ssr: false, // 서버 사이드 렌더링 비활성화
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={cn("min-h-screen bg-[#E0E5F7]", fontSans.variable)}>
        <ClientOnlyContext>{children}</ClientOnlyContext>
      </body>
    </html>
  )
}
