import type { Metadata } from "next"
import { Inter as FontSans } from "next/font/google"

import RootContext from "./_context/root-context"
import { cn } from "./_lib/utils"
import "./globals.css"

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={cn("min-h-screen bg-[#E0E5F7] bg-background font-sans antialiased", fontSans.variable)}>
        <RootContext>{children}</RootContext>
      </body>
    </html>
  )
}
